export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_DATA = 'AUTH_USER_DATA';
export const AUTH_USER_CLEAR_DATA = 'AUTH_USER_CLEAR_DATA';
export const AUTH_CLEAR_USER_ERROR = 'AUTH_CLEAR_USER_ERROR';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const LAYOUT_ITEM_MENU = 'LAYOUT_ITEM_MENU';





