export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_DATA = 'AUTH_USER_DATA';
export const AUTH_USER_CLEAR_DATA = 'AUTH_USER_CLEAR_DATA';
export const AUTH_USER_SEND_EMAIL_SUCCESS = 'AUTH_USER_SEND_EMAIL_SUCCESS';
export const AUTH_USER_CLEAR_SEND_EMAIL = 'AUTH_USER_CLEAR_SEND_EMAIL';
export const AUTH_CLEAR_USER_ERROR = 'AUTH_CLEAR_USER_ERROR';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const LAYOUT_ITEM_MENU = 'LAYOUT_ITEM_MENU';

export const USER_LOAD = 'USER_LOAD';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USER_DELETE_LOAD = 'USER_DELETE_LOAD';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_CLEAR_SUCCESS = 'USER_DELETE_CLEAR_SUCCESS';
export const USER_CLEAR_ERROR = 'USER_CLEAR_ERROR';
export const USER_ERROR = 'USER_ERROR';

export const CITY_LOAD = 'CITY_LOAD';
export const CITIES_LIST_SUCCESS = 'CITIES_LIST_SUCCESS';
export const CITY_CLEAR_ERROR = 'CITY_CLEAR_ERROR';
export const CITY_ERROR = 'CITY_ERROR';
export const CITY_EDIT_LOAD = 'CITY_EDIT_LOAD';
export const CITY_EDIT_SUCCESS = 'CITY_EDIT_SUCCESS';
export const CITY_EDIT_CLEAR_SUCCESS = 'CITY_EDIT_CLEAR_SUCCESS';

export const OPEN_DELETE_DIALOG = 'OPEN_DELETE_DIALOG';
export const CLOSE_DELETE_DIALOG = 'CLOSE_DELETE_DIALOG';

export const COMPANY_LOAD = 'COMPANY_LOAD';
export const COMPANIES_LIST_SUCCESS = 'COMPANIES_LIST_SUCCESS';
export const COMPANY_EDIT = 'COMPANY_EDIT';
export const COMPANY_DELETE = 'COMPANY_DELETE';
export const COMPANY_CLEAR_ERROR = 'COMPANY_CLEAR_ERROR';
export const COMPANY_ERROR = 'COMPANY_ERROR';

export const AREA_EDIT_SUCCESS = 'AREA_EDIT_SUCCESS';
export const AREA_EDIT_LOAD = 'AREA_EDIT_LOAD';
export const AREA_DELETE_LOAD = 'AREA_DELETE_LOAD';
export const AREA_DELETE_SUCCESS = 'AREA_DELETE_SUCCESS';
export const AREA_DELETE_CLEAR_ERROR = 'AREA_DELETE_CLEAR_ERROR';
export const AREA_DELETE_CLEAR_SUCCESS = 'AREA_DELETE_CLEAR_SUCCESS';
export const AREA_DELETE_ERROR = 'AREA_DELETE_ERROR';

export const ASSIGN_QUESTION_BY_LEVEL_LOAD = 'ASSIGN_QUESTION_BY_LEVEL_LOAD';
export const ASSIGN_QUESTION_BY_LEVEL_SUCCESS = 'ASSIGN_QUESTION_BY_LEVEL_SUCCESS';
export const ASSIGN_QUESTION_BY_LEVEL_CLEAR_SUCCESS = 'ASSIGN_QUESTION_BY_LEVEL_CLEAR_SUCCESS';
export const ASSIGN_QUESTION_BY_LEVEL_ERROR = 'ASSIGN_QUESTION_BY_LEVEL_ERROR';
export const ASSIGN_QUESTION_BY_LEVEL_CLEAR_ERROR = 'ASSIGN_QUESTION_BY_LEVEL_CLEAR_ERROR';

export const REMOVE_QUESTION_BY_LEVEL_LOAD = 'REMOVE_QUESTION_BY_LEVEL_LOAD';
export const REMOVE_QUESTION_BY_LEVEL_SUCCESS = 'REMOVE_QUESTION_BY_LEVEL_SUCCESS';
export const REMOVE_QUESTION_BY_LEVEL_CLEAR_SUCCESS = 'REMOVE_QUESTION_BY_LEVEL_CLEAR_SUCCESS';
export const REMOVE_QUESTION_BY_LEVEL_ERROR = 'REMOVE_QUESTION_BY_LEVEL_ERROR';
export const REMOVE_QUESTION_BY_LEVEL_CLEAR_ERROR = 'REMOVE_QUESTION_BY_LEVEL_CLEAR_ERROR';

export const GAME_ONE_LIST_LOAD = 'GAME_ONE_LIST_LOAD';
export const GAME_ONE_LIST_SUCCESS = 'GAME_ONE_LIST_SUCCESS';
export const GAME_ONE_LIST_CLEAR_ERROR = 'GAME_ONE_LIST_CLEAR_ERROR';
export const GAME_ONE_LIST_ERROR = 'GAME_ONE_LIST_ERROR';


export const QUESTION_BANKS_LIST_LOAD = 'QUESTION_BANKS_LIST_LOAD';
export const QUESTION_BANKS_LIST_SUCCESS = 'QUESTION_BANKS_LIST_SUCCESS';
export const QUESTION_BANK_DETAILS = 'QUESTION_BANK_DETAILS';
export const QUESTION_BANK_CLEAR_ERROR = 'QUESTION_BANK_CLEAR_ERROR';
export const QUESTION_BANK_ERROR = 'QUESTION_BANK_ERROR';

export const LEVEL_ACTIVATOR_LIST_LOAD = 'LEVEL_ACTIVATOR_LOAD';
export const LEVEL_ACTIVATOR_LIST_SUCCESS = 'LEVEL_ACTIVATOR_SUCCESS';
export const LEVEL_ACTIVATOR_LIST_CLEAR_ERROR = 'LEVEL_ACTIVATOR_CLEAR_ERROR';
export const LEVEL_ACTIVATOR_LIST_ERROR = 'LEVEL_ACTIVATOR_ERROR';
export const LEVEL_ACTIVATOR_EDIT_LOAD = 'LEVEL_ACTIVATOR_EDIT_LOAD';
export const LEVEL_ACTIVATOR_EDIT_SUCCESS = 'LEVEL_ACTIVATOR_EDIT_SUCCESS';
export const LEVEL_ACTIVATOR_EDIT_CLEAR_SUCCESS = 'LEVEL_ACTIVATOR_EDIT_CLEAR_SUCCESS';

export const CLASSIFIED_NUMBER_LIST_LOAD = 'CLASSIFIED_NUMBER_LIST_LOAD';
export const CLASSIFIED_NUMBER_LIST_SUCCESS = 'CLASSIFIED_NUMBER_LIST_SUCCESS';
export const CLASSIFIED_NUMBER_LIST_ERROR = 'CLASSIFIED_NUMBER_LIST_ERROR';
export const CLASSIFIED_NUMBER_LIST_CLEAR_ERROR = 'CLASSIFIED_NUMBER_LIST_ERROR';
export const CLASSIFIED_NUMBER_EDIT_LOAD = 'CLASSIFIED_NUMBER_EDIT_LOAD';
export const CLASSIFIED_NUMBER_EDIT_SUCCESS = 'CLASSIFIED_NUMBER_EDIT_SUCCESS'
export const CLASSIFIED_NUMBER_EDIT_CLEAR_SUCCESS = 'CLASSIFIED_NUMBER_EDIT_CLEAR_SUCCESS';

export const WE_ALL_RESPOND_RANKINGS_LIST_LOAD = 'WE_ALL_RESPOND_RANKINGS_LIST_LOAD';
export const WE_ALL_RESPOND_RANKINGS_LIST_SUCCESS = 'WE_ALL_RESPOND_RANKINGS_LIST_SUCCESS';
export const WE_ALL_RESPOND_RANKINGS_LIST_CLEAR_ERROR = 'WE_ALL_RESPOND_RANKINGS_LIST_CLEAR_ERROR';
export const WE_ALL_RESPOND_RANKINGS_LIST_ERROR = 'WE_ALL_RESPOND_RANKINGS_LIST_ERROR';

export const QUESTION_BANK_CREATE_LOAD = 'QUESTION_BANK_CREATE_LOAD';
export const QUESTION_BANK_CREATE_SUCCESS = 'QUESTION_BANK_CREATE_SUCCESS';
export const QUESTION_BANK_CREATE_CLEAR_SUCCESS = 'QUESTION_BANK_CREATE_CLEAR_SUCCESS';
export const QUESTION_BANK_CREATE_CLEAR_ERROR = 'QUESTION_BANK_CREATE_CLEAR_ERROR';
export const QUESTION_BANK_CREATE_ERROR = 'QUESTION_BANK_CREATE_ERROR';

export const QUESTION_BANK_EDIT_LOAD = 'QUESTION_BANK_EDIT_LOAD';
export const QUESTION_BANK_EDIT_SUCCESS = 'QUESTION_BANK_EDIT_SUCCESS';
export const QUESTION_BANK_EDIT_CLEAR_SUCCESS = 'QUESTION_BANK_EDIT_CLEAR_SUCCESS';
export const QUESTION_BANK_EDIT_CLEAR_ERROR = 'QUESTION_BANK_EDIT_CLEAR_ERROR';
export const QUESTION_BANK_EDIT_ERROR = 'QUESTION_BANK_EDIT_ERROR';

export const QUESTION_BANK_DELETE_LOAD = 'QUESTION_BANK_DELETE_LOAD';
export const QUESTION_BANK_DELETE_SUCCESS = 'QUESTION_BANK_DELETE_SUCCESS';
export const QUESTION_BANK_DELETE_CLEAR_SUCCESS = 'QUESTION_BANK_DELETE_CLEAR_SUCCESS';
export const QUESTION_BANK_DELETE_CLEAR_ERROR = 'QUESTION_BANK_DELETE_CLEAR_ERROR';
export const QUESTION_BANK_DELETE_ERROR = 'QUESTION_BANK_DELETE_ERROR';

export const QUESTION_BANK_SET_5050_LOAD = 'QUESTION_BANK_SET_5050_LOAD';
export const QUESTION_BANK_SET_5050_SUCCESS = 'QUESTION_BANK_SET_5050_SUCCESS';
export const QUESTION_BANK_SET_5050_CLEAR_SUCCESS = 'QUESTION_BANK_SET_5050_CLEAR_SUCCESS';
export const QUESTION_BANK_SET_5050_CLEAR_ERROR = 'QUESTION_BANK_SET_5050_CLEAR_ERROR';
export const QUESTION_BANK_SET_5050_ERROR = 'QUESTION_BANK_SET_5050_ERROR';

export const QUESTION_BANK_SET_EMMA_HELP_LOAD = 'QUESTION_BANK_SET_EMMA_HELP_LOAD';
export const QUESTION_BANK_SET_EMMA_HELP_SUCCESS = 'QUESTION_BANK_SET_EMMA_HELP_SUCCESS';
export const QUESTION_BANK_SET_EMMA_HELP_CLEAR_SUCCESS = 'QUESTION_BANK_SET_EMMA_HELP_CLEAR_SUCCESS';
export const QUESTION_BANK_SET_EMMA_HELP_CLEAR_ERROR = 'QUESTION_BANK_SET_EMMA_HELP_CLEAR_ERROR';
export const QUESTION_BANK_SET_EMMA_HELP_ERROR = 'QUESTION_BANK_SET_EMMA_HELP_ERROR';

export const QUESTION_BANK_SET_CORRECT_ANSWER_LOAD = 'QUESTION_BANK_SET_CORRECT_ANSWER_LOAD';
export const QUESTION_BANK_SET_CORRECT_ANSWER_SUCCESS = 'QUESTION_BANK_SET_CORRECT_ANSWER_SUCCESS';
export const QUESTION_BANK_SET_CORRECT_ANSWER_CLEAR_SUCCESS = 'QUESTION_BANK_SET_CORRECT_ANSWER_CLEAR_SUCCESS';
export const QUESTION_BANK_SET_CORRECT_ANSWER_CLEAR_ERROR = 'QUESTION_BANK_SET_CORRECT_ANSWER_CLEAR_ERROR';
export const QUESTION_BANK_SET_CORRECT_ANSWER_ERROR = 'QUESTION_BANK_SET_CORRECT_ANSWER_ERROR';

export const QUESTION_BANK_ANSWER_CREATE_LOAD = 'QUESTION_BANK_ANSWER_CREATE_LOAD';
export const QUESTION_BANK_ANSWER_CREATE_SUCCESS = 'QUESTION_BANK_ANSWER_CREATE_SUCCESS';
export const QUESTION_BANK_ANSWER_CREATE_CLEAR_SUCCESS = 'QUESTION_BANK_ANSWER_CREATE_CLEAR_SUCCESS';
export const QUESTION_BANK_ANSWER_CREATE_CLEAR_ERROR = 'QUESTION_BANK_ANSWER_CREATE_CLEAR_ERROR';
export const QUESTION_BANK_ANSWER_CREATE_ERROR = 'QUESTION_BANK_ANSWER_CREATE_ERROR';

export const QUESTION_BANK_ANSWER_EDIT_LOAD = 'QUESTION_BANK_ANSWER_EDIT_LOAD';
export const QUESTION_BANK_ANSWER_EDIT_SUCCESS = 'QUESTION_BANK_ANSWER_EDIT_SUCCESS';
export const QUESTION_BANK_ANSWER_EDIT_CLEAR_SUCCESS = 'QUESTION_BANK_ANSWER_EDIT_CLEAR_SUCCESS';
export const QUESTION_BANK_ANSWER_EDIT_CLEAR_ERROR = 'QUESTION_BANK_ANSWER_EDIT_CLEAR_ERROR';
export const QUESTION_BANK_ANSWER_EDIT_ERROR = 'QUESTION_BANK_ANSWER_EDIT_ERROR';

export const QUESTION_BANK_ANSWER_DELETE_LOAD = 'QUESTION_BANK_ANSWER_DELETE_LOAD';
export const QUESTION_BANK_ANSWER_DELETE_SUCCESS = 'QUESTION_BANK_ANSWER_DELETE_SUCCESS';
export const QUESTION_BANK_ANSWER_DELETE_CLEAR_SUCCESS = 'QUESTION_BANK_ANSWER_DELETE_CLEAR_SUCCESS';
export const QUESTION_BANK_ANSWER_DELETE_CLEAR_ERROR = 'QUESTION_BANK_ANSWER_DELETE_CLEAR_ERROR';
export const QUESTION_BANK_ANSWER_DELETE_ERROR = 'QUESTION_BANK_ANSWER_DELETE_ERROR';

export const WE_ALL_CONCENTRATE_RANKINGS_LIST_LOAD  = 'WE_ALL_CONCENTRATE_RANKINGS_LIST_LOAD';
export const WE_ALL_CONCENTRATE_RANKINGS_LIST_SUCCESS = 'WE_ALL_CONCENTRATE_RANKINGS_LIST_SUCCESS';
export const WE_ALL_CONCENTRATE_RANKINGS_LIST_CLEAR_ERROR = 'WE_ALL_CONCENTRATE_RANKINGS_LIST_CLEAR_ERROR';
export const WE_ALL_CONCENTRATE_RANKINGS_LIST_ERROR = 'WE_ALL_CONCENTRATE_RANKINGS_LIST_ERROR';

export const WE_ALL_KNOW_RANKINGS_LIST_LOAD =  'WE_ALL_KNOW_RANKINGS_LIST_LOAD';
export const WE_ALL_KNOW_RANKINGS_LIST_SUCCESS = 'WE_ALL_KNOW_RANKINGS_LIST_SUCCESS';
export const WE_ALL_KNOW_RANKINGS_LIST_CLEAR_ERROR = 'WE_ALL_KNOW_RANKINGS_LIST_CLEAR_ERROR';
export const WE_ALL_KNOW_RANKINGS_LIST_ERROR = 'WE_ALL_KNOW_RANKINGS_LIST_ERROR';

export const ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_LOAD = 'ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_LOAD';
export const ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_SUCCESS = 'ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_SUCCESS';
export const ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_CLEAR_SUCCESS = 'ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_CLEAR_SUCCESS';
export const ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_ERROR = 'ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_ERROR';
export const ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_CLEAR_ERROR = 'ALL_KNOW_ASSIGN_QUESTION_BY_LEVEL_CLEAR_ERROR';

export const ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_LOAD = 'ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_LOAD';
export const ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_SUCCESS = 'ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_SUCCESS';
export const ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_CLEAR_SUCCESS = 'ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_CLEAR_SUCCESS';
export const ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_ERROR = 'ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_ERROR';
export const ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_CLEAR_ERROR = 'ALL_KNOW_REMOVE_QUESTION_BY_LEVEL_CLEAR_ERROR';

export const GAME_THREE_LIST_LOAD = 'GAME_THREE_LIST_LOAD';
export const GAME_THREE_LIST_SUCCESS = 'GAME_THREE_LIST_SUCCESS';
export const GAME_THREE_LIST_CLEAR_ERROR = 'GAME_THREE_LIST_CLEAR_ERROR';
export const GAME_THREE_LIST_ERROR = 'GAME_THREE_LIST_ERROR';

export const CARD_BANKS_LIST_LOAD = 'CARD_BANKS_LIST_LOAD';
export const CARD_BANKS_LIST_SUCCESS = 'CARD_BANKS_LIST_SUCCESS';
export const CARD_BANK_DETAILS = 'CARD_BANK_DETAILS';
export const CARD_BANK_CLEAR_ERROR = 'CARD_BANK_CLEAR_ERROR';
export const CARD_BANK_ERROR = 'CARD_BANK_ERROR';

export const NEW_CARD_BANKS_LIST_LOAD = 'NEW_CARD_BANKS_LIST_LOAD';
export const NEW_CARD_BANKS_LIST_SUCCESS = 'NEW_CARD_BANKS_LIST_SUCCESS';
export const NEW_CARD_BANK_ERROR = 'NEW_CARD_BANK_ERROR';
export const NEW_CARD_BANK_CLEAR_ERROR = 'NEW_CARD_BANK_CLEAR_ERROR';

export const CARD_BANK_CREATE_LOAD = 'CARD_BANK_CREATE_LOAD';
export const CARD_BANK_CREATE_SUCCESS = 'CARD_BANK_CREATE_SUCCESS';
export const CARD_BANK_CREATE_CLEAR_SUCCESS = 'CARD_BANK_CREATE_CLEAR_SUCCESS';
export const CARD_BANK_CREATE_CLEAR_ERROR = 'CARD_BANK_CREATE_CLEAR_ERROR';
export const CARD_BANK_CREATE_ERROR = 'CARD_BANK_CREATE_ERROR';

export const CARD_BANK_EDIT_LOAD = 'CARD_BANK_EDIT_LOAD';
export const CARD_BANK_EDIT_SUCCESS = 'CARD_BANK_EDIT_SUCCESS';
export const CARD_BANK_EDIT_CLEAR_SUCCESS = 'CARD_BANK_EDIT_CLEAR_SUCCESS';
export const CARD_BANK_EDIT_CLEAR_ERROR = 'CARD_BANK_EDIT_CLEAR_ERROR';
export const CARD_BANK_EDIT_ERROR = 'CARD_BANK_EDIT_ERROR';

export const CARD_BANK_UPLOAD_IMAGE_LOAD = 'CARD_BANK_UPLOAD_IMAGE_LOAD';
export const CARD_BANK_UPLOAD_IMAGE_SUCCESS = 'CARD_BANK_UPLOAD_IMAGE_SUCCESS';
export const CARD_BANK_UPLOAD_IMAGE_CLEAR_SUCCESS = 'CARD_BANK_UPLOAD_IMAGE_CLEAR_SUCCESS';
export const CARD_BANK_UPLOAD_IMAGE_CLEAR_ERROR = 'CARD_BANK_UPLOAD_IMAGE_CLEAR_ERROR';
export const CARD_BANK_UPLOAD_IMAGE_ERROR = 'CARD_BANK_UPLOAD_IMAGE_ERROR';

export const CARD_BANK_DELETE_LOAD = 'CARD_BANK_DELETE_LOAD';
export const CARD_BANK_DELETE_SUCCESS = 'CARD_BANK_DELETE_SUCCESS';
export const CARD_BANK_DELETE_CLEAR_SUCCESS = 'CARD_BANK_DELETE_CLEAR_SUCCESS';
export const CARD_BANK_DELETE_CLEAR_ERROR = 'CARD_BANK_DELETE_CLEAR_ERROR';
export const CARD_BANK_DELETE_ERROR = 'CARD_BANK_DELETE_ERROR';

export const GAME_TWO_LIST_LOAD = 'GAME_TWO_LIST_LOAD';
export const GAME_TWO_LIST_SUCCESS = 'GAME_TWO_LIST_SUCCESS';
export const GAME_TWO_LIST_CLEAR_ERROR = 'GAME_TWO_LIST_CLEAR_ERROR';
export const GAME_TWO_LIST_ERROR = 'GAME_TWO_LIST_ERROR';

export const ASSIGN_CARD_BY_LEVEL_LOAD = 'ASSIGN_CARD_BY_LEVEL_LOAD';
export const ASSIGN_CARD_BY_LEVEL_SUCCESS = 'ASSIGN_CARD_BY_LEVEL_SUCCESS';
export const ASSIGN_CARD_BY_LEVEL_CLEAR_SUCCESS = 'ASSIGN_CARD_BY_LEVEL_CLEAR_SUCCESS';
export const ASSIGN_CARD_BY_LEVEL_ERROR = 'ASSIGN_CARD_BY_LEVEL_ERROR';
export const ASSIGN_CARD_BY_LEVEL_CLEAR_ERROR = 'ASSIGN_CARD_BY_LEVEL_CLEAR_ERROR';

export const REMOVE_CARD_BY_LEVEL_LOAD = 'REMOVE_CARD_BY_LEVEL_LOAD';
export const REMOVE_CARD_BY_LEVEL_SUCCESS = 'REMOVE_CARD_BY_LEVEL_SUCCESS';
export const REMOVE_CARD_BY_LEVEL_CLEAR_SUCCESS = 'REMOVE_CARD_BY_LEVEL_CLEAR_SUCCESS';
export const REMOVE_CARD_BY_LEVEL_ERROR = 'REMOVE_CARD_BY_LEVEL_ERROR';
export const REMOVE_CARD_BY_LEVEL_CLEAR_ERROR = 'REMOVE_CARD_BY_LEVEL_CLEAR_ERROR';